### ISSUE TITLE
No source code

### ISSUE THREAD

**Issue by ssathya** [AvapiDotNet/Avapi#1]
Code folder has only one file README.md. 
No licensing info proved at https://www.nuget.org/packages/Avapi/  or https://github.com/AvapiDotNet.

**Comment by sgiulians** [comment]
Hi ssathya,

Code folder has only one file on purpose for now. 
The licensing info is not provided for now so it's fully copyrighted by default for now (it will change soon).

We haven't decided whether publish the code or not yet because it's  all auto-generated from a tool that has been developed internally and for which we are not willing to share the code yet as it's in an early stage of development.

**Comment by VictorioBerra** [comment]
@sgiulians @AvapiDotNet @engantoniopapa 

Its been a couple years now, can you please slap a license on it and upload the source?

There are a few other FOSS projects here for people looking for a library they can use in commercial products:

https://github.com/LutsenkoKirill/AlphaVantage.Net

https://github.com/ExusAltimus/AlphaVantage.NET

**Comment by sgiulians** [comment]
Hey hello Victorio,
we have added the license many months ago. Feel free to use it: https://www.nuget.org/packages/Avapi/
Anyway, I am planning to release the source code very soon..
Have a good one.
-Simo
